spring:
  application:
    name: t1-java-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml

  t1:
    kafka:
      bootstrap-servers: localhost:9092
      consumer:
        transaction-event-group-id: transaction-event-group
        session-timeout-ms: 45000
        max-partition-fetch-bytes: 300000
        max-poll-records: 1
        max-poll-interval-ms: 300000
        heartbeat-interval: 3000
        enable-auto-commit: false
      producer:
        enable: true
      topic:
        accept_transactions: t1_demo_transaction_accept
        result_transactions: t1_demo_transaction_result
      listener:
        poll-timeout: 1000

server:
  port: 8081

logging:
  level:
    ROOT: DEBUG
    org.apache.kafka: INFO
    org.hibernate.SQL: INFO

t1:
  scan-path: ru.t1.java.demo

scheduler:
  transactions-count-limit: 10
  transactions-time-limit: 60
  cron: "0 0,20,40 * * * *"
  zone: "Europe/Moscow"